services:
  mysql-products:
    container_name: mysql-products
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: products_db
    volumes:
      - mysql-products:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - ecom-net
  postgres-auth:
    container_name: postgres-auth
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    volumes:
      - postgres-auth:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    networks:
      - ecom-net

  postgres-orders:
    container_name: postgres-orders
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    volumes:
      - postgres-orders:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - ecom-net

  redis-cart:
    container_name: redis-cart
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - ecom-net

  mssql-payments:
    container_name: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@123"
    volumes:
      - mssql-payments:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - ecom-net

networks:
  ecom-net:
    driver: bridge

volumes:
  mysql-products:
  postgres-auth:
  postgres-orders:
  mssql-payments:
