spring:
  application:
    name: api-gateway

# JWT Configuration
jwt:
  public-key: ${PUBLIC_KEY}

server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/