services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: products_db
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - ecom-net
  postgres-auth:
    container_name: postgres-auth
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    volumes:
      - postgres_auth:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    networks:
      - ecom-net

networks:
  ecom-net:
    driver: bridge

volumes:
  mysql: